- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Create a new database with name 'testdb'
    mysql_db:
      name: testdb
      state: present
  - name: Create mysql user
    mysql_user:
      name: test
      password: test
      priv: '*.*:ALL'
      state: present